site_name: fsing 
theme: 
  name: material
  icon:
    logo: material/library
    admonition:
      abstract: fontawesome/brands/bilibili
  palette:
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色（按钮也算）
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  language: zh
  icon:
    annotation: material/star-four-points-circle # 注释图标
nav:
  - 主页:
    - Home: index.md 
plugins:
  - mermaid2:
      arguments:
        theme: light

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  
extra:
  homepage: https://fsing111.github.io/fsing/ 
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/348450385?spm_id_from=333.1007.0.0
      name: Bilibili | fsing # 鼠标悬浮提示
    - icon: fontawesome/brands/accessible-icon
      link: https://github.com/fsing111/fsing/tree/master
      name: GitHub | fsing的仓库 
    - icon: fontawesome/brands/github
      link: https://github.com/fsing111
      name: GitHub | fsing 
## [bottom-left corner]
copyright: Copyright &copy; 2024-现在 fsing # 左下角的版权声明
